In [3]:
filename = "data.txt"
raw_text = open(filename, "r", encoding = "utf-8").read()
raw_text = raw_text.lower()

In [1]:
# print(raw_text)

In [6]:
chars = sorted(list(set(raw_text)))
print(chars)

['\n', ' ', '!', '"', '#', '$', '%', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', '@', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [7]:
len(chars)

58

In [8]:
chars_to_int = dict((c,i) for i,c in enumerate(chars))
chars_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '#': 4,
 '$': 5,
 '%': 6,
 "'": 7,
 '(': 8,
 ')': 9,
 '*': 10,
 ',': 11,
 '-': 12,
 '.': 13,
 '/': 14,
 '0': 15,
 '1': 16,
 '2': 17,
 '3': 18,
 '4': 19,
 '5': 20,
 '6': 21,
 '7': 22,
 '8': 23,
 '9': 24,
 ':': 25,
 ';': 26,
 '?': 27,
 '@': 28,
 '[': 29,
 ']': 30,
 '_': 31,
 'a': 32,
 'b': 33,
 'c': 34,
 'd': 35,
 'e': 36,
 'f': 37,
 'g': 38,
 'h': 39,
 'i': 40,
 'j': 41,
 'k': 42,
 'l': 43,
 'm': 44,
 'n': 45,
 'o': 46,
 'p': 47,
 'q': 48,
 'r': 49,
 's': 50,
 't': 51,
 'u': 52,
 'v': 53,
 'w': 54,
 'x': 55,
 'y': 56,
 'z': 57}

In [9]:
int_to_char = dict((i,c) for i,c in enumerate(chars))
int_to_char

{0: '\n',
 1: ' ',
 2: '!',
 3: '"',
 4: '#',
 5: '$',
 6: '%',
 7: "'",
 8: '(',
 9: ')',
 10: '*',
 11: ',',
 12: '-',
 13: '.',
 14: '/',
 15: '0',
 16: '1',
 17: '2',
 18: '3',
 19: '4',
 20: '5',
 21: '6',
 22: '7',
 23: '8',
 24: '9',
 25: ':',
 26: ';',
 27: '?',
 28: '@',
 29: '[',
 30: ']',
 31: '_',
 32: 'a',
 33: 'b',
 34: 'c',
 35: 'd',
 36: 'e',
 37: 'f',
 38: 'g',
 39: 'h',
 40: 'i',
 41: 'j',
 42: 'k',
 43: 'l',
 44: 'm',
 45: 'n',
 46: 'o',
 47: 'p',
 48: 'q',
 49: 'r',
 50: 's',
 51: 't',
 52: 'u',
 53: 'v',
 54: 'w',
 55: 'x',
 56: 'y',
 57: 'z'}

In [10]:
n_chars = len(raw_text)
n_vocab = len(chars)
print("Total Characters: ", n_chars)
print("Total Vocab (Unique characters): ", n_vocab)

Total Characters:  163780
Total Vocab (Unique characters):  58


In [12]:
# prepare the dataset of input to output pairs encoded as integers 
seq_length = 15 #can be changed
dataX = []
dataY = []

for i in range(0, n_chars - seq_length, 1):
    seq_in = raw_text[i:i + seq_length]
    seq_out = raw_text[i + seq_length]
    dataX.append([chars_to_int[char] for char in seq_in])
    dataY.append(chars_to_int [seq_out])
n_patterns = len(dataY)
print("Total Patterns: ", n_patterns)

Total Patterns:  163765


In [2]:
# dataX

In [16]:
import numpy as np

X = np.reshape(dataX, (n_patterns,seq_length,1))

X = X/float(n_vocab)
print(X)

[[[0.81034483]
  [0.84482759]
  [0.79310345]
  ...
  [0.77586207]
  [0.56896552]
  [0.62068966]]

 [[0.84482759]
  [0.79310345]
  [0.70689655]
  ...
  [0.56896552]
  [0.62068966]
  [0.84482759]]

 [[0.79310345]
  [0.70689655]
  [0.62068966]
  ...
  [0.62068966]
  [0.84482759]
  [0.65517241]]

 ...

 [[0.55172414]
  [0.56896552]
  [0.79310345]
  ...
  [0.79310345]
  [0.79310345]
  [0.72413793]]

 [[0.56896552]
  [0.79310345]
  [0.89655172]
  ...
  [0.79310345]
  [0.72413793]
  [0.86206897]]

 [[0.79310345]
  [0.89655172]
  [0.87931034]
  ...
  [0.72413793]
  [0.86206897]
  [0.22413793]]]


In [22]:
X.shape

(163765, 15, 1)

In [19]:
from keras.layers.attention.multi_head_attention import activation 
from keras.api._v2.keras import Sequential
from keras.layers import LSTM, Dense, Dropout
from keras.callbacks import ModelCheckpoint
from keras.utils import np_utils

In [18]:
y = np_utils.to_categorical(dataY)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [25]:
# define the LSTM model
model = Sequential()
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2]))) #It can have 1 or more training samples 
model.add(Dropout(0.2))
model.add(Dense(y.shape[1], activation='softmax'))

#compile
model.compile(loss="categorical_crossentropy", optimizer='adam')

# define the checkpoint
filepath="weights-improvement-{epoch:02d}-{loss:.4f}.hdf5"
checkpoint = ModelCheckpoint (filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]

In [26]:
epochs = 10
batch_size = 128

model.fit(X, y, epochs=epochs, batch_size=batch_size, callbacks=callbacks_list)

Epoch 1/10
1280/1280 [==============================] - ETA: 0s - loss: 2.9906
Epoch 1: loss improved from inf to 2.99056, saving model to weights-improvement-01-2.9906.hdf5
1280/1280 [==============================] - 102s 78ms/step - loss: 2.9906
Epoch 2/10
1279/1280 [============================>.] - ETA: 0s - loss: 2.8001
Epoch 2: loss improved from 2.99056 to 2.80003, saving model to weights-improvement-02-2.8000.hdf5
1280/1280 [==============================] - 94s 73ms/step - loss: 2.8000
Epoch 3/10
1280/1280 [==============================] - ETA: 0s - loss: 2.7181
Epoch 3: loss improved from 2.80003 to 2.71810, saving model to weights-improvement-03-2.7181.hdf5
1280/1280 [==============================] - 94s 73ms/step - loss: 2.7181
Epoch 4/10
1279/1280 [============================>.] - ETA: 0s - loss: 2.6609
Epoch 4: loss improved from 2.71810 to 2.66083, saving model to weights-improvement-04-2.6608.hdf5
1280/1280 [==============================] - 89s 70ms/step - loss: 2.

In [27]:
filename = 'weights-improvement-10-2.4071.hdf5' 
model.load_weights(filename)
model.compile(loss="categorical_crossentropy", optimizer='adam')

In [37]:
# generate a random seed
print(len(dataX))
start = np.random.randint(0, len(dataX)-1) 
print(start)
pattern = dataX[start] #datax contains list of patterns print("Seed: ")
print("\"",' '.join([int_to_char[value] for value in pattern]), "\"")

163765
129331
" s o - - a n d   w h a t   w i "


In [38]:
# generate characters
length = 10
final = []
for i in range(length):
    # reshaping the seed sequence before passing it into the LSTM model
    x = np.reshape(pattern, (1, len(pattern), 1))
    #print(x)
    # normalizing the integer values
    x = x / float(n_vocab)
    # print(x)
    # making prediction
    prediction = model.predict(x, verbose=0)
    # Get the predicted value with maximum probability 
    index= np.argmax(prediction)
    # Convert the predicted integer to char
    result = int_to_char[index]
    #print (result)
    final.append(result)
    # Adding the predicted character to the sequence sequence
    pattern.append(index)
    # Removing the first character from the seed sequence 
    pattern = pattern[1:len(pattern)]
print(final)

['u', ' ', 'w', 'o', ' ', 'l', 'e', 'k', 'e', ' ']
